name = "gleam_and_typescript"
version = "1.0.0"
target = "javascript"

[dependencies]
gleam_stdlib = "~> 0.34 or ~> 1.0"

[dev-dependencies]
gleeunit = "~> 1.0"

[javascript]
typescript_declarations = true